version: '2'

services:
  nginx:
    build: .
    container_name: proxy
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./certs/letsupscale.com/cert-IUNJKSYUFCWDXCWNHAOJQEVPUGR43RKQ.pem:/certs/letsupscale.com/cert-IUNJKSYUFCWDXCWNHAOJQEVPUGR43RKQ.pem
      - ./certs/letsupscale.com/pk-IUNJKSYUFCWDXCWNHAOJQEVPUGR43RKQ.pem:/certs/letsupscale.com/pk-IUNJKSYUFCWDXCWNHAOJQEVPUGR43RKQ.pem

networks: 
  mainet: